# VAPI Professional Configuration File
# Voice AI Platform Settings with Advanced Features

# Assistant Configuration
assistants:
  - name: "Voice AI Professional Assistant"
    model: "gpt-4"
    voice: "alloy"
    webhook_url: "http://localhost:5678/webhook/voice-trigger"
    language: "en"
    interruption_threshold: 0.5
    max_duration: 300
    initial_message: "Hello! I'm your professional AI assistant. How can I help you today?"
    sentiment_analysis: true
    timezone_aware: true
    
  - name: "Customer Service Professional Bot"
    model: "gpt-4"
    voice: "echo"
    webhook_url: "http://localhost:5678/webhook/customer-service"
    language: "en"
    interruption_threshold: 0.3
    max_duration: 600
    initial_message: "Welcome to professional customer service. I'm here to help you with any questions or issues."
    sentiment_analysis: true
    timezone_aware: true

# Voice Settings
voice_settings:
  default_voice: "alloy"
  available_voices:
    - "alloy"
    - "echo"
    - "fable"
    - "onyx"
    - "nova"
    - "shimmer"
  
  language_support:
    - "en"  # English
    - "es"  # Spanish
    - "fr"  # French
    - "de"  # German
    - "it"  # Italian
    - "pt"  # Portuguese
    - "ja"  # Japanese
    - "ko"  # Korean
    - "zh"  # Chinese

# Webhook Configuration
webhooks:
  - name: "n8n_voice_trigger"
    url: "http://localhost:5678/webhook/voice-trigger"
    events:
      - "call_started"
      - "call_ended"
      - "speech_started"
      - "speech_ended"
      - "transcript"
      - "function_call"
      - "sentiment_analysis"
      - "timezone_detection"
    
  - name: "n8n_customer_service"
    url: "http://localhost:5678/webhook/customer-service"
    events:
      - "call_started"
      - "call_ended"
      - "transcript"
      - "function_call"
      - "sentiment_analysis"
    
  - name: "n8n_email_callback"
    url: "http://localhost:5678/webhook/email-callback"
    events:
      - "call_ended"
      - "followup_triggered"
      - "email_sent"

# Function Calls (for RAG and Memory integration)
function_calls:
  - name: "query_knowledge_base"
    description: "Query the knowledge base for relevant information"
    parameters:
      type: "object"
      properties:
        query:
          type: "string"
          description: "The search query"
        user_id:
          type: "string"
          description: "User identifier"
        context:
          type: "string"
          description: "Conversation context"
        sentiment:
          type: "string"
          description: "User sentiment analysis"
      required: ["query", "user_id"]
    
  - name: "update_memory"
    description: "Update user conversation memory"
    parameters:
      type: "object"
      properties:
        user_id:
          type: "string"
          description: "User identifier"
        conversation_data:
          type: "object"
          description: "Conversation data to store"
        preferences:
          type: "object"
          description: "User preferences"
        timezone:
          type: "string"
          description: "User timezone"
      required: ["user_id", "conversation_data"]
    
  - name: "schedule_callback"
    description: "Schedule a follow-up callback"
    parameters:
      type: "object"
      properties:
        user_id:
          type: "string"
          description: "User identifier"
        callback_type:
          type: "string"
          description: "Type of callback (email, sms, call)"
        scheduled_time:
          type: "string"
          description: "When to schedule the callback"
        timezone:
          type: "string"
          description: "User timezone"
        message:
          type: "string"
          description: "Callback message"
      required: ["user_id", "callback_type", "scheduled_time", "timezone"]
    
  - name: "send_email"
    description: "Send a follow-up email"
    parameters:
      type: "object"
      properties:
        to:
          type: "string"
          description: "Recipient email"
        subject:
          type: "string"
          description: "Email subject"
        body:
          type: "string"
          description: "Email body"
        template_id:
          type: "string"
          description: "Email template to use"
      required: ["to", "subject", "body"]

# Call Settings
call_settings:
  max_duration: 600  # 10 minutes
  recording_enabled: true
  transcript_enabled: true
  real_time_transcript: true
  sentiment_analysis: true
  timezone_detection: true
  
  # Interruption settings
  interruption_threshold: 0.5
  silence_timeout: 3.0
  
  # Audio settings
  sample_rate: 16000
  channels: 1
  bit_rate: 16
  
  # Professional features
  call_summary: true
  followup_scheduling: true
  email_integration: true

# Integration Settings
integrations:
  rag_api:
    base_url: "http://localhost:8080"
    timeout: 30
    retry_attempts: 3
    
  memory_api:
    base_url: "http://localhost:8001"
    timeout: 10
    retry_attempts: 2
    
  n8n_webhook:
    base_url: "http://localhost:5678"
    timeout: 15
    retry_attempts: 2
    
  email_service:
    smtp_host: "smtp.gmail.com"
    smtp_port: 587
    username: "${EMAIL_USERNAME}"
    password: "${EMAIL_PASSWORD}"
    use_tls: true
    
  timezone_service:
    default_timezone: "America/New_York"
    supported_timezones:
      - "America/New_York"
      - "America/Chicago"
      - "America/Denver"
      - "America/Los_Angeles"
      - "Europe/London"
      - "Europe/Paris"
      - "Asia/Tokyo"
      - "Australia/Sydney"

# Security Settings
security:
  api_key_required: true
  webhook_signature_verification: true
  rate_limiting:
    enabled: true
    max_requests_per_minute: 100
    max_requests_per_hour: 1000
  
  # Professional security features
  ssl_required: true
  encryption_at_rest: true
  audit_logging: true

# Logging Configuration
logging:
  level: "info"
  format: "json"
  output: "stdout"
  
  # Log retention
  retention_days: 30
  max_file_size: "100MB"
  
  # Sensitive data masking
  mask_fields:
    - "api_key"
    - "phone_number"
    - "email"
    - "password"
    - "credit_card"
  
  # Professional logging
  audit_log: true
  performance_log: true
  error_tracking: true

# Performance Settings
performance:
  max_concurrent_calls: 50
  memory_limit: "2GB"
  cpu_limit: "4"
  
  # Caching
  cache_enabled: true
  cache_ttl: 3600  # 1 hour
  
  # Connection pooling
  pool_size: 10
  pool_timeout: 30
  
  # Professional performance
  load_balancing: true
  auto_scaling: true
  health_checks: true

# Monitoring
monitoring:
  health_check_enabled: true
  metrics_enabled: true
  prometheus_endpoint: "/metrics"
  
  # Alert thresholds
  alerts:
    high_error_rate: 0.05  # 5%
    slow_response_time: 3.0  # 3 seconds
    high_memory_usage: 0.8  # 80%
    low_call_quality: 0.7  # 70%
  
  # Professional monitoring
  real_time_dashboard: true
  custom_metrics: true
  alert_notifications: true

# Professional Features
professional_features:
  # Email Integration
  email_templates:
    - id: "call_summary"
      subject: "Your Call Summary"
      body: "Thank you for your call. Here's your summary: {{summary}}"
    - id: "followup"
      subject: "Follow-up from your call"
      body: "We'd like to follow up on your recent call: {{details}}"
    - id: "appointment"
      subject: "Appointment Confirmation"
      body: "Your appointment has been confirmed for {{datetime}}"
  
  # Callback System
  callback_types:
    - "email"
    - "sms"
    - "call"
    - "calendar_invite"
  
  # Timezone Features
  timezone_detection:
    enabled: true
    auto_adjust: true
    user_preference: true
  
  # Sentiment Analysis
  sentiment_analysis:
    enabled: true
    real_time: true
    escalation_threshold: 0.3
  
  # Call Quality
  call_quality:
    monitoring: true
    recording: true
    transcription: true
    sentiment_tracking: true 
